import sys
import os
import datetime as dt
import unittest

projectDir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.join(projectDir, 'pyHimawari8'))

from helper import parseTime


class Test(unittest.TestCase):

    @classmethod
    def setUpClass(self):
        print('Start to test helper.py...')

    @classmethod
    def tearDownClass(self):
        print('Finish testing helper.py!')

    def setUp(self):
        print("execute setUp")

    def tearDown(self):
        print("execute tearDown")

    def test_parseTime(self):
        print('---> Test on parseTime')

        thisTime = parseTime(
            'NC_H08_20200101_0000_L2CLP010_FLDK.02401_02401.nc',
            ft='CLP', pLe='L2')

        self.assertEqual(thisTime, dt.datetime(2020, 1, 1, 0, 0, 0))


def main():

    suite = unittest.TestSuite()

    tests = [
        Test('test_parseTime')
        ]   # setup the test list
    suite.addTests(tests)

    # print the test report as html file
    # with open('HTMLReport.html', 'w') as f:
    #     runner = HTMLTestRunner(stream=f,
    #                             title='MathFunc Test Report',
    #                             description='generated by HTMLTestRunner.',
    #                             verbosity=2
    #                             )
    #     runner.run(suite)

    # print the test report to the console
    runner = unittest.TextTestRunner(verbosity=2)
    runner.run(suite)


if __name__ == '__main__':
    main()
