# JAXAFTP_MP = "/mnt/ftp_mount_point/jma/hsd"   # root directory of Himawari-8 HSD
JAXAFTP_MP = '/'
JAXAFTP_LINK = ''
IMG_DIR = '/'
BDY_DIR = ''   # baidu yun sync directory

LAT_RANGE = [15, 58]
LON_RANGE = [70, 140]